### ISSUE TITLE
UTF8 chars broken after reconnecting to MySQL

### ISSUE THREAD

**Issue by schmengler** [integer-net/solr-magento1#4]
This issue comes from IntegerNet_Solr_Model_Resource_Db::disconnectMysql which closes SQL connections during indexing.

When new queries are made after that, the connection is re-initialized but this time it will not run 
`<initStatements>` from `app/etc/local.xml` which often has to be "SET NAMES utf8".

Commenting the code for connection closing in disconnectMysql() resolves the issue.

**Comment by schmengler** [comment]
Related commit: db3e2b427c28fd95f0ee8a07ebbe35087ac3d4b1

**Comment by avstudnitz** [comment]
@schmengler This should be resolved, right?
