### ISSUE TITLE
"There is no active transaction" error on product save

### ISSUE THREAD

**Issue by schmengler** [integer-net/solr-magento1#6]

**Comment by schmengler** [comment]
index is "update on save"

**Comment by avstudnitz** [comment]
I just had the same problem with the latest pro version and Magento 1.9.3.1. I created a new simple product and saved it. Saving was successful, but I got  the above mentioned error message, even on saving the product again.

**Comment by schmengler** [comment]
Cannot reproduce it with integernet-solr 1.7.2 and Magento 1.9.3.1, let's look into it together
